# Scratch Perceptron
Let's create an Artificial Neural Network by scratch using only numpy, specifically we'll program a Perceptron. This lecture was created from "Polycode" in his video "Create a Simple Neural Network in Python from Scratch".

### Problem Set
<img src="images/sp/problem_set.png" height="65%" width="65%"></img>

### Perceptron
<img src="images/sp/perceptron.png" height="50%" width="50%"></img>

We're going to program a perceptron (no hidden layers) to solve this deep learning problem.

### Sigmoid Activation (Normalization) Function
<img src="images/sp/sigmoid.png" height="65%" width="65%"></img

We're going to use the sigmoid activation function to normalize the input values.

In [1]:
# import numpy
import numpy as np

In [2]:
# the independent variables for training
x_train = np.array([
    [0, 0, 1],
    [1, 1, 1],
    [1, 0, 1],
    [0, 1, 1]
])

# the dependent variables for training
y_train = np.array([
    [0],
    [1],
    [1],
    [1]
])

In [3]:
# set the randomization seed
np.random.seed(1)

# because we have 3 inputs (columns) and 1 output, initialize a 3x1 matrix with values close to 0
synaptic_weights = 2 * np.random.random((3, 1)) - 1

synaptic_weights

array([[-0.16595599],
       [ 0.44064899],
       [-0.99977125]])

In [4]:
# sigmoid activation function
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [5]:
# derivative of sigmoid activation function
def sigmoid_derivative(x):
    return np.exp(x) / np.square((1 + np.exp(x)))

In [6]:
epochs = 20000
for epoch in range(epochs):
    # y_pred is the sigmoid multiplication of the training set and synaptic weights
    y_pred = sigmoid(np.dot(x_train, synaptic_weights))

    # receive the error by subtracting the actual from the predicted values of the training set
    error = y_train - y_pred
    
    """
    implement gradient descent: weight adjustments equal to error times
    sigmoid derivative because we used the sigmoid function as the cost function
    to determine the difference (error) of the actual and predicted values.
    """
    adjustments = error * sigmoid_derivative(y_pred)
    
    # sum the new weights of the synapses with the multiplication of training set and adjustments
    synaptic_weights += np.dot(x_train.T, adjustments)

In [7]:
print("Synaptic Weights:")
print(synaptic_weights)

Synaptic Weights:
[[14.48501619]
 [14.48501743]
 [-6.90407232]]


In [8]:
# predicted values after fitting the training set
print("Predicted Training Set:")
print(y_pred)
print()

# actual values of the training set
print("Actual Training Set:")
print(y_train)

Predicted Training Set:
[[0.00100273]
 [1.        ]
 [0.99949015]
 [0.99949016]]

Actual Training Set:
[[0]
 [1]
 [1]
 [1]]
